from selenium.webdriver.common.keys import Keys

WEB_VIRTUAL_KEYS = {

    "Enter": (Keys.ENTER, ),
    "F1": (Keys.F1, ),
    "F2": (Keys.F2, ),
    "F3": (Keys.F3, ),
    "F4": (Keys.F4, ),
    "F5": (Keys.F5, ),
    "F6": (Keys.F6, ),
    "F7": (Keys.F7, ),
    "F8": (Keys.F8, ),
    "F9": (Keys.F9, ),
    "F10": (Keys.F10, ),
    "Ctrl+S": (Keys.CONTROL, 's'),
    "F12": (Keys.F12, ),
    "Shift+F1": (Keys.SHIFT, Keys.F1),
    "Shift+F2": (Keys.SHIFT, Keys.F2),
    "Shift+F3": (Keys.SHIFT, Keys.F3),
    "Shift+F4": (Keys.SHIFT, Keys.F4),
    "Shift+F5": (Keys.SHIFT, Keys.F5),
    "Shift+F6": (Keys.SHIFT, Keys.F6),
    "Shift+F7": (Keys.SHIFT, Keys.F7),
    "Shift+F8": (Keys.SHIFT, Keys.F8),
    "Shift+F9": (Keys.SHIFT, Keys.F9),
    "Shift+Ctrl+0": (Keys.SHIFT, Keys.CONTROL, '0'),
    "Shift+F11": (Keys.SHIFT, Keys.F11),
    "Shift+F12": (Keys.SHIFT, Keys.F12),
    "Ctrl+F1": (Keys.CONTROL, Keys.F1),
    "Ctrl+F2": (Keys.CONTROL, Keys.F2),
    "Ctrl+F3": (Keys.CONTROL, Keys.F3),
    "Ctrl+F4": (Keys.CONTROL, Keys.F4),
    "Ctrl+F5": (Keys.CONTROL, Keys.F5),
    "Ctrl+F6": (Keys.CONTROL, Keys.F6),
    "Ctrl+F7": (Keys.CONTROL, Keys.F7),
    "Ctrl+F8": (Keys.CONTROL, Keys.F8),
    "Ctrl+F9": (Keys.CONTROL, Keys.F9),
    "Ctrl+F10": (Keys.CONTROL, Keys.F10),
    "Ctrl+F11": (Keys.CONTROL, Keys.F11),
    "Ctrl+F12": (Keys.CONTROL, Keys.F12),
    "Ctrl+Shift+F1": (Keys.CONTROL, Keys.SHIFT, Keys.F1),
    "Ctrl+Shift+F2": (Keys.CONTROL, Keys.SHIFT, Keys.F2),
    "Ctrl+Shift+F3": (Keys.CONTROL, Keys.SHIFT, Keys.F3),
    "Ctrl+Shift+F4": (Keys.CONTROL, Keys.SHIFT, Keys.F4),
    "Ctrl+Shift+F5": (Keys.CONTROL, Keys.SHIFT, Keys.F5),
    "Ctrl+Shift+F6": (Keys.CONTROL, Keys.SHIFT, Keys.F6),
    "Ctrl+Shift+F7": (Keys.CONTROL, Keys.SHIFT, Keys.F7),
    "Ctrl+Shift+F8": (Keys.CONTROL, Keys.SHIFT, Keys.F8),
    "Ctrl+Shift+F9": (Keys.CONTROL, Keys.SHIFT, Keys.F9),
    "Ctrl+Shift+F10": (Keys.CONTROL, Keys.SHIFT, Keys.F10),
    "Ctrl+Shift+F11": (Keys.CONTROL, Keys.SHIFT, Keys.F11),
    "Ctrl+Shift+F12": (Keys.CONTROL, Keys.SHIFT, Keys.F12),
    "Ctrl+E": (Keys.CONTROL, 'e'),
    "Ctrl+F": (Keys.CONTROL, 'f'),
    "Ctrl+/": (Keys.CONTROL, Keys.SEPARATOR),
    "Ctrl+N": (Keys.CONTROL, 'n'),
    "Ctrl+O": (Keys.CONTROL, 'o'),
    "Ctrl+X": (Keys.CONTROL, 'x'),
    "Ctrl+C": (Keys.CONTROL, 'c'),
    "Ctrl+V": (Keys.CONTROL, 'v'),
    "Ctrl+Z": (Keys.CONTROL, 'z'),
    "Ctrl+PageUp": (Keys.CONTROL, Keys.PAGE_UP),
    "PageUp": (Keys.PAGE_UP, ),
    "PageDown": (Keys.PAGE_DOWN, ),
    "Ctrl+PageDown": (Keys.CONTROL, Keys.PAGE_DOWN),
    "Ctrl+G": (Keys.CONTROL, 'g'),
    "Ctrl+R": (Keys.CONTROL, 'r'),
    "Ctrl+P": (Keys.CONTROL, 'p'),
}
